### ISSUE TITLE
importlib.metadata.PackageNotFoundError: No package metadata was found for upscale_ncnn_py

### ISSUE THREAD

**Issue by justinjohn0306** [NevermindNilas/TheAnimeScripter#27]

**Comment by NevermindNilas** [comment]
Hi, are you using the 1.7.0 release or self built?

**Comment by justinjohn0306** [comment]
> Hi, are you using the 1.7.0 release or self built?

self built with python 3.11

**Comment by justinjohn0306** [comment]
Okay so I just read the updated readme and ran the ``pip install -r requirements-dev.txt`` cmd and that did the trick :)

**Comment by NevermindNilas** [comment]
The reason you got warning from Defender is because you are running an unsigned executable on your system.

Unsigned meaning with no license attached to it which tells Microsof and by that extension Windows Defender that this is a " legit " software.

There is no bypassing that, it has nothing to do with my system or yours it's just how Windows operates.
