### ISSUE TITLE
GUI: Parameters are passed to main even for operations that are not enabled

### ISSUE THREAD

**Issue by przemoc** [NevermindNilas/TheAnimeScripter#34]
Captured the situation after clicking Run (which does not work for me, but that's a separate issue):
![image](https://github.com/NevermindNilas/TheAnimeScripter/assets/142372/23cfbd9b-0d83-4933-8487-4b4c1e2624ef)

In the screenshot no operation is selected.

Log:

`Settings saved successfully`
`C:\Tools\TAS\main.exe --input "c:/users/przemoc/videos/zoomit.mp4" --output "c:/users/przemoc/videos/zoomit-test.mp4" --resize_factor 1 --interpolate_factor 2 --upscale_factor 2 --interpolate_method rife4.17 --upscale_method shufflecugan --denoise_method dpir --dedup_method ssim --depth_method small --encode_method x264 --resize_method bilinear`

We can see that parameters are passed even for operations that have not been enabled (empty checkboxes).

**Comment by NevermindNilas** [comment]
Those ops are irrelevant for the most part since the actual `initiator` usually are commands that follow the format  `--dedup`.
You can safely ignore them since they will not work unless the checkbox relevant to them are active.

You can read more about the 'on / off' commands in [parameters](https://github.com/NevermindNilas/TheAnimeScripter/blob/main/PARAMETERS.MD)
