### ISSUE TITLE
GUI: Do not convert file paths from "Input Path" and "Output Path" to lower-case when building command to run.

### ISSUE THREAD

**Issue by przemoc** [NevermindNilas/TheAnimeScripter#35]
Users typically want to be in control of how their files are named, including using upper or lower case letters. Right now TAS GUI does not allow that.

**Comment by NevermindNilas** [comment]
True, that's an oversight on my side.

**Comment by NevermindNilas** [comment]
Fixed with: https://github.com/NevermindNilas/TheAnimeScripter/commit/59c04a9259759f719e821eb1998a4ab572d52449
![image](https://github.com/NevermindNilas/TheAnimeScripter/assets/128264457/55375f4a-cd13-4a08-ac9a-e983d9efcf85)

Also went ahead and added a warning for when input path is empty:
![image](https://github.com/NevermindNilas/TheAnimeScripter/assets/128264457/540a3cde-61fb-4aed-b7f5-8d423860b259)
