### ISSUE TITLE
GUI: Support defining custom encoding settings

### ISSUE THREAD

**Issue by przemoc** [NevermindNilas/TheAnimeScripter#36]
Until user does final encoding pass (which may not necessarily happen in TAS), user may want to work with lossless or almost lossless quality.

E.g. for x264 it may be
`-c:v libx264 -crf 0 -profile:v high444 -pix_fmt yuv444p10le`
or
`-c:v libx264 -crf 0 -profile:v high444 -pix_fmt yuv444p`

There may be other valid reasons to have custom encoding settings.

**Comment by NevermindNilas** [comment]
TAS used to be hardcoded to decode in `rgb24 raw` so it was working as lossless throughout the process as it could. 

Ever since switching to `decord` I lost track of it but I didn't see any color shifts or abnormalities at least `visually` when comparing 1.8.0 results to newer releases ( 1.8.5 specifically ).

As for encoding, TAS does technically support `--custom_encoder` which does provide more granularity to the encoding parameters but it can easily break how TAS works. This feature has yet to be added to the standalone GUI but it is present in the After Effects GUI.

**Comment by przemoc** [comment]
Oh, I see. Sorry for overlooking `--custom_encoder`. So I guess the issue remains only on standalone GUI side of things.

**Comment by NevermindNilas** [comment]
Finished.

**Comment by przemoc** [comment]
Month ago, after I realized custom encoding settings were available in CLI, but not in GUI, I renamed issue to make it strictly GUI related.
You closed a few days ago, yet I do not see any improvements in GUI related to that in v1.9.0, so I think it should be kept open.
Did I miss anything?

**Comment by NevermindNilas** [comment]
Hi,

As stated in the release 1.9.0
`Standalone GUI with TAURI: GUI.exe is no longer going to be maintained in favor of Tauri for a planned 2.0.0 release.`

I will no longer be maintaining the current iteration of the GUI and will instead focus on an alternative with TAURI at its core.
That one already has a 'half baked' custom encoder in it.

The current GUI is just frankly bad and I am not happy with constantly releasing the GUI with a ' maybe works ' state.

**Comment by przemoc** [comment]
Thank you for explaining.
