### ISSUE TITLE
GUI: Use alternative way to start command than by doing it directly via `cmd`

### ISSUE THREAD

**Issue by przemoc** [NevermindNilas/TheAnimeScripter#38]
Starting via `cmd` does not work when user uses [Legacy Console mode](https://learn.microsoft.com/en-us/windows/console/legacymode) as has been discussed in:
- #33

For Windows 10+ users Windows Terminal is possibly predominantly available nowadays (but I don't remember if it was preinstalled from the get go), so using `wt cmd` instead of `cmd` may be good enough solution for everyone.

There may be some better ways, but that would possibly require some research.

**Comment by NevermindNilas** [comment]
WT should only be preinstalled on W11 afaik and a huge portion of the user base is still on W10.

But if it is that easy maybe a try / except could technically work. Will look into it tomorrow.

**Comment by NevermindNilas** [comment]
Fixed with: https://github.com/NevermindNilas/TheAnimeScripter/commit/afb5d22404dbec4c028ee04420d74a5e258868df

![image](https://github.com/NevermindNilas/TheAnimeScripter/assets/128264457/12f016de-a67c-4df8-8f4d-d97d04ddc336)
![image](https://github.com/NevermindNilas/TheAnimeScripter/assets/128264457/6ce5c04b-edb5-4de5-b3b1-67f84946686a)

TAS will now dynamically switch between whichever terminal is present with preference for WT for the added benefits of better visuals.
