### ISSUE TITLE
GUI: Add "Keep command prompt after running" option to support running command without closing window after it finishes

### ISSUE THREAD

**Issue by przemoc** [NevermindNilas/TheAnimeScripter#39]
Right now running command via CMD with `/C` is hardcoded. When new option would be selected:

- [ ] Keep command prompt after running

then running command via CMD with `/K` could be used instead.

```
C:\Users\przemoc>cmd /?
Starts a new instance of the Windows command interpreter

CMD [/A | /U] [/Q] [/D] [/E:ON | /E:OFF] [/F:ON | /F:OFF] [/V:ON | /V:OFF]
    [[/S] [/C | /K] string]

/C      Carries out the command specified by string and then terminates
/K      Carries out the command specified by string but remains
...
```

**Comment by NevermindNilas** [comment]
This is the invoke command for the terminal
```py
            os.system(f'start cmd /c "{command} & exit"')
```

I am not sure if I can reuse the same terminal due to the nature of os.system / subprocess. The only solution I can think of is using a `.bat` file.

**Comment by przemoc** [comment]
> I am not sure if I can reuse the same terminal

That's a secondary thing here. Even if you cannot reuse them and each Run will create new window, then I believe it's fine.
The point is to not have vanishing command prompt window upon completion, which may be seen as a debug option, especially when command finishes quickly (e.g. due to some failure).

I just realized that due to TAS having `& exit`, even with `/K` it would close afterward.
You would need to get rid of `& exit` first - not sure what was the use case that led you to add it there.

Alternatively, you could replace `& exit` with `& pause` when proposed option would be selected, then you could continue using `/C`.

**Comment by NevermindNilas** [comment]
`& exit` was added just to make sure that it closes because occasionally it would hang if the process didn't exit gracefully, I am not sure why that was and nor am I sure if I can even reproduce it anymore but I just added it just to be sure. I will see if I can remove it. 

99% of the issues are logged in the file `log.txt` and the rest are super edge case situations ( like the terminal thing we discussed earlier ) or stuff that I break because I am trying to squeeze out every inch of performance out of Python and that can lead to stuff breaking quite often ( hence why the GUI sometimes works sometimes doesn't ).

This is something I will consider to add but it's a 50-50 situation because the terminal approach that TAS took with 1.8.5+ is a temporary fix so that the progress bar ( that everyone on discord asked for ) could work.

I will direct my focus on improving the overall UI / UX experience and making the GUI " prettier " but I never liked designing GUIs all that much and I will take every shortcut I can to getting it to a " technically works " state.

**Comment by NevermindNilas** [comment]
Added new option with commit: https://github.com/NevermindNilas/TheAnimeScripter/commit/305aed0f9398ac10620133e0292b79837c262b56

![image](https://github.com/NevermindNilas/TheAnimeScripter/assets/128264457/d9606633-86d3-49d1-b646-d8038977439e)
