### ISSUE TITLE
Black screen Frame Interpolation output

### ISSUE THREAD

**Issue by Palatinik** [NevermindNilas/TheAnimeScripter#64]
I'm trying to use Frame Interpolation in a 25 sec. to 46 sec. clip, but every attempt so far has given me a black video with less than 2MB of size, I'm not sure what I'm doing wrong, I've tried on both After Effects and Premiere, on pretty much every Rife version (for ALL GPUs, I'm running AMD), the source file is about 31MB.

After Effects just outputs a blank file with audio (when there is audio on the file), Premiere gives me a "Error Importing Output" generic error, and still produces the same blank file.

![Captura de tela 2024-12-28 153900](https://github.com/user-attachments/assets/b403445e-233e-4a0d-af13-c96d0fd8979d)

![Captura de tela 2024-12-28 153918](https://github.com/user-attachments/assets/ca8e13b9-54ae-4883-b2ed-c81ee2afcd07)

![Captura de tela 2024-12-28 153945](https://github.com/user-attachments/assets/024610cf-5ed3-4194-91ca-ee53a6764307)

![unknown_2024 12 28-15 49](https://github.com/user-attachments/assets/e8df697b-932c-4a89-a2f1-3ccceff0107e)

![Adobe Premiere Pro 2020_2024 12 28-15 45](https://github.com/user-attachments/assets/617e89d3-1b0b-4991-9595-855d08442cc0)

I'm running a RX6750XT and a Ryzen 9 5900XT with 32GBs of RAM

**Comment by NevermindNilas** [comment]
Hello,

This was an oversight on my side when I released 1.9.11 and has been fixed with the latest TAS nightly.

https://github.com/NevermindNilas/TAS-Nightly

If you use TAS' Adobe Extension, I have recently released for the discord members a Release Candidate 2 for TAS 2.0.0 specifically that has all of the fixes in place as well as a bunch of new ones.
https://discordapp.com/channels/1041502781808328704/1175113031223623791/1321638282672738328

[TheAnimeScripter-2.0.0-RC2.zip](https://github.com/user-attachments/files/18267368/TheAnimeScripter-2.0.0-RC2.zip)

If you wish to upgrade to 2.0.0 you will have to download the adobe extension linked in that discord server or use the one I sent above and follow the manual installation guide linked below in order to place the dependencies in the right folder:
https://github.com/NevermindNilas/TheAnimeScripter/wiki/Installation-Guide-for-TAS%E2%80%90Adobe-Edition-in-case-of-errors

( Make sure to use the .exe from TAS-Nightly and not from this repository )

As a side note, I have yet to provide official support for Premiere since I lack the time necessary to work on it, but I would love to hear your feedback on how well does it perform and what features do and do not work in it ( apart from the aforementioned interpolation ).

Thank you!

**Comment by Palatinik** [comment]
I'll update it now, bless, thank you for the quick response brother!

**Comment by Palatinik** [comment]
Interpolation worked, thanks again!

![Captura de tela 2024-12-28 161929](https://github.com/user-attachments/assets/b10d39a8-c1a4-4b9e-b3ee-14e569a5e480)

**Comment by NevermindNilas** [comment]
You're welcome!
